name: Zaxe Web API | CI

on:
  push:
    branches: ['live']
  pull_request:
    branches: ['live']

env:
  CI: true
  SMTP_EMAIL_ADDRESS: ${{secrets.SMTP_EMAIL_ADDRESS}}
  SMTP_EMAIL_PORT: ${{secrets.SMTP_EMAIL_PORT}}
  SMTP_USER_NAME: ${{secrets.SMTP_USER_NAME}}
  SMTP_USER_PASSWORD: ${{secrets.SMTP_USER_PASSWORD}}
  WOOCOMMERCE_API_URL: ${{secrets.WOOCOMMERCE_API_URL}}
  WOOCOMMERCE_API_CONSUMER_KEY: ${{secrets.WOOCOMMERCE_API_CONSUMER_KEY}}
  WOOCOMMERCE_API_CONSUMER_SECRET_KEY: ${{secrets.WOOCOMMERCE_API_CONSUMER_SECRET_KEY}}
  GOOGLE_SERVICE_ACCOUNT: ${{secrets.GOOGLE_SERVICE_ACCOUNT}}
  SPREADSHEET_CONTACT_ID: ${{secrets.SPREADSHEET_CONTACT_ID}}
  SPREADSHEET_TALKTOSALES_ID: ${{secrets.SPREADSHEET_TALKTOSALES_ID}}
  SPREADSHEET_CONTACT_RANGE: ${{secrets.SPREADSHEET_CONTACT_RANGE}}
  SPREADSHEET_TALKTOSALES_RANGE: ${{secrets.SPREADSHEET_TALKTOSALES_RANGE}}
  SETROW_API_PRIVATE_KEY: ${{secrets.SETROW_API_PRIVATE_KEY}}
  SETROW_API_WEB_GROUP_ID: ${{secrets.SETROW_API_WEB_GROUP_ID}}
  SETROW_API_XDESKTOP_GROUP_ID: ${{secrets.SETROW_API_XDESKTOP_GROUP_ID}}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: yarn
      - name: Test env var
        run: echo ${{ env.SMTP_EMAIL_ADDRESS }}
      - name: Test  App
        run: yarn test:ci
